In [4]:
# dataframe 创建
import pandas as pd
import numpy as np

s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series(['a', 'b', 'c', 'd', 'e'])
df = pd.DataFrame({"第一列":s2, '第二列':s1})
df

  第一列  第二列
0   a    1
1   b    2
2   c    3
3   d    4
4   e    5

In [5]:
type(df)

pandas.DataFrame

In [6]:
type(df['第一列'])

pandas.Series

In [10]:
df = pd.DataFrame(
    {
        "name":['Tom', 'Jack', 'Alice', 'Bob', 'Charlie'],
        'age':[15, 17, 20, 26, 30],
        'score':[60.5, 80, 30.6, 70, 83.5]
    }, index= [1, 2, 3, 4, 5],
    columns=['name', 'age', 'score']
)
df

      name  age  score
1      Tom   15   60.5
2     Jack   17   80.0
3    Alice   20   30.6
4      Bob   26   70.0
5  Charlie   30   83.5

In [11]:
print('行索引')
df.index

行索引

Index([1, 2, 3, 4, 5], dtype='int64')

In [12]:
df.columns # 列标签

Index(['name', 'age', 'score'], dtype='str')

In [13]:
df.values # 值

array([['Tom', 15, 60.5],
       ['Jack', 17, 80.0],
       ['Alice', 20, 30.6],
       ['Bob', 26, 70.0],
       ['Charlie', 30, 83.5]], dtype=object)

In [14]:
df.ndim # 维度

2

In [15]:
df.dtypes # 类型

name         str
age        int64
score    float64
dtype: object

In [16]:
df.shape # 形状

(5, 3)

In [17]:
df.size # 元素个数

15

In [18]:
df.T # 转置

          1     2      3     4        5
name    Tom  Jack  Alice   Bob  Charlie
age      15    17     20    26       30
score  60.5  80.0   30.6  70.0     83.5

In [19]:
df.T.columns

Index([1, 2, 3, 4, 5], dtype='int64')

In [20]:
df.T.index

Index(['name', 'age', 'score'], dtype='str')

In [21]:
df

      name  age  score
1      Tom   15   60.5
2     Jack   17   80.0
3    Alice   20   30.6
4      Bob   26   70.0
5  Charlie   30   83.5

In [22]:
df.loc[4]

name      Bob
age        26
score    70.0
Name: 4, dtype: object

In [23]:
df.iloc[3]

name      Bob
age        26
score    70.0
Name: 4, dtype: object

In [24]:
df.loc[:,'name']

1        Tom
2       Jack
3      Alice
4        Bob
5    Charlie
Name: name, dtype: str

In [26]:
df.loc[:2,:]

   name  age  score
1   Tom   15   60.5
2  Jack   17   80.0

In [27]:
df

      name  age  score
1      Tom   15   60.5
2     Jack   17   80.0
3    Alice   20   30.6
4      Bob   26   70.0
5  Charlie   30   83.5

In [28]:
df.at[3, 'score']

np.float64(30.6)

In [29]:
df.iat[2, 1]

np.int64(20)

In [30]:
df['name']

1        Tom
2       Jack
3      Alice
4        Bob
5    Charlie
Name: name, dtype: str

In [31]:
df.name

1        Tom
2       Jack
3      Alice
4        Bob
5    Charlie
Name: name, dtype: str

In [33]:
# 查看部分数据
print(df.head(3))

    name  age  score
1    Tom   15   60.5
2   Jack   17   80.0
3  Alice   20   30.6

In [34]:
df.tail(2)

      name  age  score
4      Bob   26   70.0
5  Charlie   30   83.5

In [35]:
df

      name  age  score
1      Tom   15   60.5
2     Jack   17   80.0
3    Alice   20   30.6
4      Bob   26   70.0
5  Charlie   30   83.5

In [40]:
df[df.score>70]

      name  age  score
2     Jack   17   80.0
5  Charlie   30   83.5

In [39]:
df[(df.score>70) & (df.age<20)]

   name  age  score
2  Jack   17   80.0

In [45]:
# 随机抽样
df.sample(4)

      name  age  score
4      Bob   26   70.0
3    Alice   20   30.6
2     Jack   17   80.0
5  Charlie   30   83.5

In [49]:
df.isin(['Jack', 20])

    name    age  score
1  False  False  False
2   True  False  False
3  False   True  False
4  False  False  False
5  False  False  False

In [50]:
df.sum()

name     TomJackAliceBobCharlie
age                         108
score                     324.6
dtype: object

In [51]:
df['score'].sum().round(1)

np.float64(324.6)

In [52]:
df.score.max()

np.float64(83.5)

In [53]:
df.age.min()

np.int64(15)

In [54]:
df.score.mean()

np.float64(64.92)

In [56]:
df.score.median()

np.float64(70.0)

In [60]:
df.describe().round(1)

        age  score
count   5.0    5.0
mean   21.6   64.9
std     6.3   21.2
min    15.0   30.6
25%    17.0   60.5
50%    20.0   70.0
75%    26.0   80.0
max    30.0   83.5

In [63]:
df = pd.DataFrame(
    {
        "name":['Tom', 'Jack', 'Alice', 'Bob', 'Charlie', 'Bob'],
        'age':[15, 17, 20, 26, 30, 26],
        'score':[60.5, 80, 30.6, 70, 83.5, 70]
    }, index= [1, 2, 3, 4, 5, 6],
    columns=['name', 'age', 'score']
)
print(df.value_counts()) #出现次数

name     age  score
Bob      26   70.0     2
Tom      15   60.5     1
Jack     17   80.0     1
Alice    20   30.6     1
Charlie  30   83.5     1
Name: count, dtype: int64

In [64]:
df.sample(2)

      name  age  score
5  Charlie   30   83.5
2     Jack   17   80.0

In [65]:
df.replace(15, 30)

      name  age  score
1      Tom   30   60.5
2     Jack   17   80.0
3    Alice   20   30.6
4      Bob   26   70.0
5  Charlie   30   83.5
6      Bob   26   70.0

In [66]:
df

      name  age  score
1      Tom   15   60.5
2     Jack   17   80.0
3    Alice   20   30.6
4      Bob   26   70.0
5  Charlie   30   83.5
6      Bob   26   70.0

In [69]:
df.cumsum()
df.cummin()

    name  age  score
1    Tom   15   60.5
2   Jack   15   60.5
3  Alice   15   30.6
4  Alice   15   30.6
5  Alice   15   30.6
6  Alice   15   30.6

In [71]:
print(df.sort_index(ascending=False))

      name  age  score
6      Bob   26   70.0
5  Charlie   30   83.5
4      Bob   26   70.0
3    Alice   20   30.6
2     Jack   17   80.0
1      Tom   15   60.5

In [74]:
df.sort_values(by=['age','score'], ascending=[False,True])

      name  age  score
5  Charlie   30   83.5
4      Bob   26   70.0
6      Bob   26   70.0
3    Alice   20   30.6
2     Jack   17   80.0
1      Tom   15   60.5

In [75]:
df.nlargest(2, columns=['score', 'age'])

      name  age  score
5  Charlie   30   83.5
2     Jack   17   80.0