In [2]:
'''
案例1：学生成绩分析
场景：某班级的学生成绩数据如下，请完成以下任务：
1. 计算每位学生的总分和平均分。
2. 找出数学成绩高于90分或英语成绩高于85分的学生。
3. 按总分从高到低排序，并输出前3名学生。
'''
import pandas as pd
data = {
    '姓名': ['张三', '李四', '王五', '赵六', '钱七'],
    '数学': [85, 92, 78, 88, 95],
    '英语': [90, 88, 85, 92, 80],
    '物理': [75, 80, 88, 85, 90]
}
scores = pd.DataFrame(data)
scores

   姓名  数学  英语  物理
0  张三  85  90  75
1  李四  92  88  80
2  王五  78  85  88
3  赵六  88  92  85
4  钱七  95  80  90

In [8]:
# 每位学生的总分和平均分
scores['总分'] = scores[['数学','英语','物理']].sum(axis=1)
scores['平均分'] = scores[['数学','英语','物理']].mean(axis=1).round(1)
scores

   姓名  数学  英语  物理   总分   平均分
0  张三  85  90  75  250  83.3
1  李四  92  88  80  260  86.7
2  王五  78  85  88  251  83.7
3  赵六  88  92  85  265  88.3
4  钱七  95  80  90  265  88.3

In [9]:
# 找出数学成绩高于 90 或英语成绩高于 85 的学生
scores[(scores['数学']>90)|(scores['英语']>85)]

   姓名  数学  英语  物理   总分   平均分
0  张三  85  90  75  250  83.3
1  李四  92  88  80  260  86.7
3  赵六  88  92  85  265  88.3
4  钱七  95  80  90  265  88.3

In [11]:
# 按总分从高到低排序，输出前三
scores.sort_values(by='总分', ascending=False).head(3)

   姓名  数学  英语  物理   总分   平均分
3  赵六  88  92  85  265  88.3
4  钱七  95  80  90  265  88.3
1  李四  92  88  80  260  86.7

In [12]:
scores.nlargest(3, columns=['总分'])

   姓名  数学  英语  物理   总分   平均分
3  赵六  88  92  85  265  88.3
4  钱七  95  80  90  265  88.3
1  李四  92  88  80  260  86.7