In [18]:
# 缺失值的处理
import pandas as pd
import numpy as np

s = pd.Series([1, 2, np.nan, None, pd.NA])
print(s)

0       1
1       2
2     NaN
3    None
4    <NA>
dtype: object

In [19]:
# 查看是否缺失值
s.isna()

0    False
1    False
2     True
3     True
4     True
dtype: bool

In [20]:
s.isnull()

0    False
1    False
2     True
3     True
4     True
dtype: bool

In [21]:
df = pd.DataFrame([[1,pd.NA, 2], [2, 3, 5], [None, 4, 6]],columns=['第1列','第2列','第3列'])
df

   第1列   第2列  第3列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6

In [22]:
df.isna()

     第1列    第2列    第3列
0  False   True  False
1  False  False  False
2   True  False  False

In [23]:
df.isna().sum(axis=1)

0    1
1    0
2    1
dtype: int64

In [24]:
df.isna().sum()

第1列    1
第2列    1
第3列    0
dtype: int64

In [25]:
# 剔除缺失值
print(s)
print('-'*50)
print(s.dropna())

0       1
1       2
2     NaN
3    None
4    <NA>
dtype: object
--------------------------------------------------
0    1
1    2
dtype: object

In [26]:
print(df)
print('-'*50)
print(df.dropna())

print('how=all', '-'*50)
print(df.dropna(how='all'))

   第1列   第2列  第3列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6
--------------------------------------------------
   第1列 第2列  第3列
1  2.0   3    5
how=all --------------------------------------------------
   第1列   第2列  第3列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6

In [27]:
print('thresh', '-'*50)
print(df.dropna(thresh=3))

print('vertical', '-'*50)
print(df.dropna(axis=1))

thresh --------------------------------------------------
   第1列 第2列  第3列
1  2.0   3    5
vertical --------------------------------------------------
   第3列
0    2
1    5
2    6

In [28]:
print(df.dropna(subset=['第1列']))

   第1列   第2列  第3列
0  1.0  <NA>    2
1  2.0     3    5

In [29]:
#  填充缺失值
df = pd.read_csv('../data/weather_withna.csv')
df.head()

         date  precipitation  temp_max  temp_min  wind  weather
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1  2012-01-02           10.9      10.6       2.8   4.5     rain
2  2012-01-03            0.8      11.7       7.2   2.3     rain
3  2012-01-04           20.3      12.2       5.6   4.7     rain
4  2012-01-05            1.3       8.9       2.8   6.1     rain

In [30]:
df.isna().sum(axis=0)

date               0
precipitation    303
temp_max         303
temp_min         303
wind             303
weather          303
dtype: int64

In [31]:
df.head()
print(df.fillna({'temp_max':20}).tail())   # 使用字典来填充
print(df.fillna(df[['wind']].mean()).tail())    # 用统计值填充

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN      20.0       NaN   NaN     NaN
1457  2015-12-28            NaN      20.0       NaN   NaN     NaN
1458  2015-12-29            NaN      20.0       NaN   NaN     NaN
1459  2015-12-30            NaN      20.0       NaN   NaN     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min      wind weather
1456  2015-12-27            NaN       NaN       NaN  3.242055     NaN
1457  2015-12-28            NaN       NaN       NaN  3.242055     NaN
1458  2015-12-29            NaN       NaN       NaN  3.242055     NaN
1459  2015-12-30            NaN       NaN       NaN  3.242055     NaN
1460  2015-12-31           20.6      12.2       5.0  3.800000    rain

In [32]:
print(df.ffill().tail()) # 用前驱填充（传感器信号丢失）

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            0.0      11.1       4.4   4.8     sun
1457  2015-12-28            0.0      11.1       4.4   4.8     sun
1458  2015-12-29            0.0      11.1       4.4   4.8     sun
1459  2015-12-30            0.0      11.1       4.4   4.8     sun
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [33]:
print(df.bfill().tail()) # 用后继填充

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27           20.6      12.2       5.0   3.8    rain
1457  2015-12-28           20.6      12.2       5.0   3.8    rain
1458  2015-12-29           20.6      12.2       5.0   3.8    rain
1459  2015-12-30           20.6      12.2       5.0   3.8    rain
1460  2015-12-31           20.6      12.2       5.0   3.8    rain