# 数据变形

In [11]:
import pandas as pd
data = {
    'ID' : [1, 2],
    'name' : ['alice', 'bob'],
    'Math' : [90, 85],
    'English' : [88, 92],
    'Science' : [95, 89]
}
df = pd.DataFrame(data)
df

   ID   name  Math  English  Science
0   1  alice    90       88       95
1   2    bob    85       92       89

In [12]:
# 宽表转换成长表
df2 = pd.melt(df, id_vars=['ID', 'name'],
            var_name='Subject', value_name='Score'
            , value_vars=['Math', 'English', 'Science']
            )
df2

   ID   name  Subject  Score
0   1  alice     Math     90
1   2    bob     Math     85
2   1  alice  English     88
3   2    bob  English     92
4   1  alice  Science     95
5   2    bob  Science     89

In [13]:
# 长表转宽表
pd.pivot(df2, index=['ID', 'name'], columns=['Subject'], values='Score')

Subject   English  Math  Science
ID name
1  alice       88    90       95
2  bob         92    85       89

# 关于分列

In [14]:
data1 = {
    'ID' : [1, 2],
    'name' : ['alice smith', 'bob smith'],
    'Math' : [90, 85],
    'English' : [88, 92],
    'Science' : [95, 89]
}
df = pd.DataFrame(data1)
df

   ID         name  Math  English  Science
0   1  alice smith    90       88       95
1   2    bob smith    85       92       89

In [15]:
df[['first', 'last']] = df['name'].str.split(' ', expand=True)
df

   ID         name  Math  English  Science  first   last
0   1  alice smith    90       88       95  alice  smith
1   2    bob smith    85       92       89    bob  smith

In [16]:
# 例子
df = pd.read_csv('../data/sleep.csv')
df = df[['person_id', 'blood_pressure']]
df.tail()

     person_id blood_pressure
395        396         118/66
396        397         132/80
397        398         125/76
398        399         130/75
399        400         118/70

In [17]:
df[['high', 'low']] = df['blood_pressure'].str.split('/', expand=True)
df[['high', 'low']]

    high low
0    124  70
1    131  86
2    122  70
3    124  72
4    133  78
..   ...  ..
395  118  66
396  132  80
397  125  76
398  130  75
399  118  70

[400 rows x 2 columns]

In [18]:
df['high'] = df['high'].astype('float64')
df['low'] = df['low'].astype('float64')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   person_id       400 non-null    int64
 1   blood_pressure  400 non-null    str
 2   high            400 non-null    float64
 3   low             400 non-null    float64
dtypes: float64(2), int64(1), str(1)
memory usage: 12.6 KB

In [19]:
df.tail()

     person_id blood_pressure   high   low
395        396         118/66  118.0  66.0
396        397         132/80  132.0  80.0
397        398         125/76  125.0  76.0
398        399         130/75  130.0  75.0
399        400         118/70  118.0  70.0

In [20]:
df.high.mean()

np.float64(122.19)