In [24]:
# 时间的处理
import pandas as pd
d = pd.Timestamp('2015-05-02 10:22')
d

Timestamp('2015-05-02 10:22:00')

In [25]:
print(type(d))

<class 'pandas.Timestamp'>

In [26]:
print('年', d.year)
print('月', d.month)
print('日', d.day)
print(d.hour, d.minute, d.second)
print('季度', d.quarter)
print('是否 d.is_xxx')
print('是否闰年', d.is_leap_year)

年 2015
月 5
日 2
10 22 0
季度 2
是否 d.is_xxx
是否闰年 False

In [27]:
print('星期几', d.day_name())
print('转换为天',d.to_period('D'))
print('转换为季度:', d.to_period('Q'))
print('年度', d.to_period('Y'))
print('月度', d.to_period('M'))
print('周维度', d.to_period('W'))

星期几 Saturday
转换为天 2015-05-02
转换为季度: 2015Q2
年度 2015
月度 2015-05
周维度 2015-04-27/2015-05-03

In [28]:
# 字符串转换为日期类型
a = pd.to_datetime('2015-02-28 10:22')
a

Timestamp('2015-02-28 10:22:00')

In [29]:
print(type(a))

<class 'pandas.Timestamp'>

In [30]:
# dataFrame 日期转换
df = pd.DataFrame({
    'sales':[100, 200, 300],
    'date': ['20250601', '20250602', '20250603']
})
df['datetime'] = pd.to_datetime(df['date'])
df

   sales      date   datetime
0    100  20250601 2025-06-01
1    200  20250602 2025-06-02
2    300  20250603 2025-06-03

In [31]:
df['day'] = df['datetime'].dt.day_name()
df

   sales      date   datetime      day
0    100  20250601 2025-06-01   Sunday
1    200  20250602 2025-06-02   Monday
2    300  20250603 2025-06-03  Tuesday

In [32]:
# 文件读取
df = pd.read_csv('../data/weather.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   str
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   str
dtypes: float64(4), str(2)
memory usage: 68.6 KB

In [33]:
df

            date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [34]:
df['datetime'] = pd.to_datetime(df['date'])
df['day'] = df['datetime'].dt.day_name()

In [35]:
df

,date,precipitation,temp_max,temp_min,wind,weather,datetime,day
0,2012-01-01,0.0,12.8,5.0,4.7,drizzle,2012-01-01,Sunday
1,2012-01-02,10.9,10.6,2.8,4.5,rain,2012-01-02,Monday
2,2012-01-03,0.8,11.7,7.2,2.3,rain,2012-01-03,Tuesday
3,2012-01-04,20.3,12.2,5.6,4.7,rain,2012-01-04,Wednesday
4,2012-01-05,1.3,8.9,2.8,6.1,rain,2012-01-05,Thursday
...,...,...,...,...,...,...,...,...
1456,2015-12-27,8.6,4.4,1.7,2.9,rain,2015-12-27,Sunday
1457,2015-12-28,1.5,5.0,1.7,1.3,rain,2015-12-28,Monday
1458,2015-12-29,0.0,7.2,0.6,2.6,fog,2015-12-29,Tuesday
1459,2015-12-30,0.0,5.6,-1.0,3.4,sun,2015-12-30,Wednesday
1460,2015-12-31,0.0,5.6,-2.1,3.5,sun,2015-12-31,Thursday

In [36]:
# CSV 导入时间转换
df = pd.read_csv('../data/weather.csv', parse_dates=['date'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   datetime64[us]
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   str
dtypes: datetime64[us](1), float64(4), str(1)
memory usage: 68.6 KB

In [37]:
# 日期数据作为索引
# df.set_index('date', inplace=True)
# df
df.set_index('date')

            precipitation  temp_max  temp_min  wind  weather
date
2012-01-01            0.0      12.8       5.0   4.7  drizzle
2012-01-02           10.9      10.6       2.8   4.5     rain
2012-01-03            0.8      11.7       7.2   2.3     rain
2012-01-04           20.3      12.2       5.6   4.7     rain
2012-01-05            1.3       8.9       2.8   6.1     rain
...                   ...       ...       ...   ...      ...
2015-12-27            8.6       4.4       1.7   2.9     rain
2015-12-28            1.5       5.0       1.7   1.3     rain
2015-12-29            0.0       7.2       0.6   2.6      fog
2015-12-30            0.0       5.6      -1.0   3.4      sun
2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 5 columns]

In [38]:
df['date'].dtypes

dtype('<M8[us]')

In [39]:
df_date = df.set_index('date')
df_date.loc['2013-01':'2014-01']

            precipitation  temp_max  temp_min  wind weather
date
2013-01-01            0.0       5.0      -2.8   2.7     sun
2013-01-02            0.0       6.1      -1.1   3.2     sun
2013-01-03            4.1       6.7      -1.7   3.0    rain
2013-01-04            2.5      10.0       2.2   2.8    rain
2013-01-05            3.0       6.7       4.4   3.1    rain
...                   ...       ...       ...   ...     ...
2014-01-27            0.0       9.4       1.7   1.3     sun
2014-01-28            8.9      11.1       6.1   1.6    rain
2014-01-29           21.6      11.1       7.2   3.4    rain
2014-01-30            0.0       8.3       6.1   6.4     sun
2014-01-31            2.3       7.8       5.6   2.6    rain

[396 rows x 5 columns]

In [40]:
d1 = pd.Timestamp('2023-04-30')
d2 = pd.Timestamp('2026-08-07')
d3 = d2 - d1
d3

Timedelta('1195 days 00:00:00')

In [41]:
df_date['delta'] = df['date'] - df['date'][0]
df_date.set_index('delta', inplace=True)
df_date.info()

<class 'pandas.DataFrame'>
TimedeltaIndex: 1461 entries, NaT to NaT
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   precipitation  1461 non-null   float64
 1   temp_max       1461 non-null   float64
 2   temp_min       1461 non-null   float64
 3   wind           1461 non-null   float64
 4   weather        1461 non-null   str
dtypes: float64(4), str(1)
memory usage: 68.5 KB

In [42]:
days = pd.date_range("2025-07-03", "2026-02-09", freq='W')
days

DatetimeIndex(['2025-07-06', '2025-07-13', '2025-07-20', '2025-07-27',
               '2025-08-03', '2025-08-10', '2025-08-17', '2025-08-24',
               '2025-08-31', '2025-09-07', '2025-09-14', '2025-09-21',
               '2025-09-28', '2025-10-05', '2025-10-12', '2025-10-19',
               '2025-10-26', '2025-11-02', '2025-11-09', '2025-11-16',
               '2025-11-23', '2025-11-30', '2025-12-07', '2025-12-14',
               '2025-12-21', '2025-12-28', '2026-01-04', '2026-01-11',
               '2026-01-18', '2026-01-25', '2026-02-01', '2026-02-08'],
              dtype='datetime64[us]', freq='W-SUN')

In [43]:
days = pd.date_range('2025-07-03', periods=10, freq='W-MON')
days

DatetimeIndex(['2025-07-07', '2025-07-14', '2025-07-21', '2025-07-28',
               '2025-08-04', '2025-08-11', '2025-08-18', '2025-08-25',
               '2025-09-01', '2025-09-08'],
              dtype='datetime64[us]', freq='W-MON')

In [44]:
days = pd.date_range('2025-07-03', periods=10, freq='QE')
days

DatetimeIndex(['2025-09-30', '2025-12-31', '2026-03-31', '2026-06-30',
               '2026-09-30', '2026-12-31', '2027-03-31', '2027-06-30',
               '2027-09-30', '2027-12-31'],
              dtype='datetime64[us]', freq='QE-DEC')

In [45]:
df = pd.read_csv('../data/weather.csv', parse_dates=['date'])
df.set_index('date', inplace=True)
df

            precipitation  temp_max  temp_min  wind  weather
date
2012-01-01            0.0      12.8       5.0   4.7  drizzle
2012-01-02           10.9      10.6       2.8   4.5     rain
2012-01-03            0.8      11.7       7.2   2.3     rain
2012-01-04           20.3      12.2       5.6   4.7     rain
2012-01-05            1.3       8.9       2.8   6.1     rain
...                   ...       ...       ...   ...      ...
2015-12-27            8.6       4.4       1.7   2.9     rain
2015-12-28            1.5       5.0       1.7   1.3     rain
2015-12-29            0.0       7.2       0.6   2.6      fog
2015-12-30            0.0       5.6      -1.0   3.4      sun
2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 5 columns]

In [46]:
df[ ["temp_max", "temp_min"] ].resample("YE").mean()

             temp_max  temp_min
date
2012-12-31  15.276776  7.289617
2013-12-31  16.058904  8.153973
2014-12-31  16.995890  8.662466
2015-12-31  17.427945  8.835616

In [47]:
df[ ["temp_max", "temp_min"] ].resample("YS").mean()

             temp_max  temp_min
date
2012-01-01  15.276776  7.289617
2013-01-01  16.058904  8.153973
2014-01-01  16.995890  8.662466
2015-01-01  17.427945  8.835616