# 关于重复数据

In [6]:
import pandas as pd
data = {
    "name" : ['alice', 'alice', 'bob', 'alice', 'jack', 'bob'],
    'age' : [26, 25, 30, 25, 35, 30],
    'city' : ['NY', 'NY', 'LA', 'NY', 'SF', 'LA']
}
df = pd.DataFrame(data)
df

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [7]:
df.duplicated() # 一整条记录都是一样的，标记为重复，返回 True

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [8]:
df.drop_duplicates()

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
4   jack   35   SF

In [9]:
df.drop_duplicates(subset=['name']) # 根据指定列去重

    name  age city
0  alice   26   NY
2    bob   30   LA
4   jack   35   SF

In [10]:
df.drop_duplicates(subset=['name'], keep='last') # 保留最后（最新）者

    name  age city
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA