# 数据分箱

In [1]:
# pd.cut(x, bins, labels)
import pandas as pd

df = pd.read_csv('../data/employees.csv')
df.head(10)

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,IT_PROG,4800.0,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,IT_PROG,4800.0,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,IT_PROG,4200.0,NaN,103.0,60.0
8,108,Nancy,Greenberg,NGREENBE,515.124.4569,FI_MGR,12000.0,NaN,101.0,100.0
9,109,Daniel,Faviet,DFAVIET,515.124.4169,FI_ACCOUNT,9000.0,NaN,108.0,100.0

In [2]:
df1 = df.head(10)[['employee_id', 'salary']]
df1

   employee_id   salary
0          100  24000.0
1          101  17000.0
2          102  17000.0
3          103   9000.0
4          104   6000.0
5          105   4800.0
6          106   4800.0
7          107   4200.0
8          108  12000.0
9          109   9000.0

In [3]:
pd.cut(df1['salary'], bins = 2)

0    (14100.0, 24000.0]
1    (14100.0, 24000.0]
2    (14100.0, 24000.0]
3     (4180.2, 14100.0]
4     (4180.2, 14100.0]
5     (4180.2, 14100.0]
6     (4180.2, 14100.0]
7     (4180.2, 14100.0]
8     (4180.2, 14100.0]
9     (4180.2, 14100.0]
Name: salary, dtype: category
Categories (2, interval[float64, right]): [(4180.2, 14100.0] < (14100.0, 24000.0]]

In [4]:
pd.cut(df1['salary'], bins = 2).value_counts()

salary
(4180.2, 14100.0]     7
(14100.0, 24000.0]    3
Name: count, dtype: int64

In [5]:
pd.cut(df['salary'], bins = [0, 10000, 20000, 30000]).value_counts()

salary
(0, 10000]        92
(10000, 20000]    14
(20000, 30000]     1
Name: count, dtype: int64

In [6]:
pd.cut(df1['salary'], bins = [0, 10000, 20000, 30000], labels=['low','middle', 'high']).value_counts()

salary
low       6
middle    3
high      1
Name: count, dtype: int64

In [7]:
df1['收入范围'] = pd.cut(df1['salary'], bins = [0, 10000, 20000, 30000], labels=['low','middle', 'high'])
df1

   employee_id   salary    收入范围
0          100  24000.0    high
1          101  17000.0  middle
2          102  17000.0  middle
3          103   9000.0     low
4          104   6000.0     low
5          105   4800.0     low
6          106   4800.0     low
7          107   4200.0     low
8          108  12000.0  middle
9          109   9000.0     low

In [8]:
pd.qcut(df1['salary'],3).value_counts()

salary
(4199.999, 6000.0]    4
(6000.0, 12000.0]     3
(12000.0, 24000.0]    3
Name: count, dtype: int64

In [9]:
# 睡眠数据
df = pd.read_csv('../data/sleep.csv')
df.head(10)
df1 = df.head(10)[['person_id', 'sleep_quality']]
df1

   person_id  sleep_quality
0          1            7.0
1          2            4.9
2          3            6.0
3          4           10.0
4          5            9.5
5          6            6.9
6          7            6.1
7          8            6.2
8          9            7.2
9         10            4.0

In [10]:
pd.cut(df['sleep_quality'], bins = 3).value_counts()

sleep_quality
(4.0, 7.0]      206
(7.0, 10.0]     129
(0.991, 4.0]     65
Name: count, dtype: int64

In [11]:
pd.qcut(df['sleep_quality'], 3).value_counts()

sleep_quality
(0.999, 5.4]    141
(5.4, 7.0]      130
(7.0, 10.0]     129
Name: count, dtype: int64

In [12]:
df1['睡眠质量'] = pd.cut(df['sleep_quality'], bins = 3, labels=['差','中', '优'])
df1

   person_id  sleep_quality 睡眠质量
0          1            7.0    中
1          2            4.9    中
2          3            6.0    中
3          4           10.0    优
4          5            9.5    优
5          6            6.9    中
6          7            6.1    中
7          8            6.2    中
8          9            7.2    优
9         10            4.0    差

In [13]:
df1['睡眠质量'].value_counts()

睡眠质量
中    6
优    3
差    1
Name: count, dtype: int64

In [14]:
# 分箱的逻辑是给数据分类
print(df1['睡眠质量'].dtypes)

category

In [15]:
df = pd.DataFrame({
    'name':['Jack', 'Alice', 'Bob', 'Charlie'],
    'age':[20, 30, 40, 50],
    'gender':['male', 'female', 'male', 'female'],
})
df.set_index('name', inplace=True)
df.reset_index(inplace=True)
df

      name  age  gender
0     Jack   20    male
1    Alice   30  female
2      Bob   40    male
3  Charlie   50  female

In [16]:
df.rename(columns={"age":"年龄"})

      name  年龄  gender
0     Jack  20    male
1    Alice  30  female
2      Bob  40    male
3  Charlie  50  female

In [17]:
df.index=[1, 2, 3, 4]
df.columns=['姓名','年龄','性别']
df

        姓名  年龄      性别
1     Jack  20    male
2    Alice  30  female
3      Bob  40    male
4  Charlie  50  female